### ISSUE TITLE
Some issue in installation in pygsl on Mac OS (with M1 chip)

### ISSUE THREAD

**Issue by adwaitk06** [pygsl/pygsl#21]
WARNING: Discarding https://files.pythonhosted.org/packages/0f/82/8bc81042923e474de30a080a551f11a4a352c098a569e6e126f313322735/pygsl-2.3.2.tar.gz#sha256=fa5d018d4421373f5390ac199bc5d484ef317d8358505b35a795bb89f96c8a9c (from https://pypi.org/simple/pygsl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  **Using cached pygsl-2.3.0.1.tar.gz (1.1 MB)**
    _ERROR: Command errored out with exit status 1:_
     command: /Users/adwaitkulkarni/Documents/apps/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/setup.py'"'"'; __file__='"'"'/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-pip-egg-info-n4q4x186
         cwd: /private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/
    Complete output (16 lines):
    /Users/adwaitkulkarni/Documents/apps/anaconda3/lib/python3.9/site-packages/setuptools/version.py:1: UserWarning: Module errno was already imported from None, but /private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a is being added to sys.path
      import pkg_resources
    /bin/sh: gsl-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/setup.py", line 99, in <module>
        from gsl_Extension import gsl_Extension
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/gsl_dist/gsl_Extension.py", line 22, in <module>
        from gsl_Location import gsl_Location
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/gsl_dist/gsl_Location.py", line 158, in <module>
        gsl_Location = _gsl_Location_gsl_config()
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/gsl_dist/gsl_Location.py", line 111, in __init__
        self.prefix         = self.get_gsl_info('--prefix').strip()
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_92117b3e8fa64e35a869283e2428474a/gsl_dist/gsl_Location.py", line 133, in get_gsl_info
        raise DistutilsExecError("could not start %s"%self.gsl_config_tool)
    distutils.errors.DistutilsExecError: could not start gsl-config
    ----------------------------------------
_WARNING: Discarding https://files.pythonhosted.org/packages/17/fc/9c11163f017a0d6877141d4d4edb619b0f05990d865caab840a2d0463581/pygsl-2.3.0.1.tar.gz#sha256=b248a899a9df0b94996fd5fe070f8ecbd3d42ca07486a829dedcdfdd70a3337d (from https://pypi.org/simple/pygsl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygsl-2.1.1.tar.gz (733 kB)_
    _ERROR: Command errored out with exit status 1:_
     command: /Users/adwaitkulkarni/Documents/apps/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/setup.py'"'"'; __file__='"'"'/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-pip-egg-info-58_14dp1
         cwd: /private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/
    Complete output (18 lines):
    /bin/sh: gsl-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/setup.py", line 74, in <module>
        from gsl_Extension import gsl_Extension
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/gsl_dist/gsl_Extension.py", line 138, in <module>
        gsl_Location = _gsl_Location_gsl_config()
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/gsl_dist/gsl_Extension.py", line 93, in __init__
        self.prefix = self.get_gsl_info('--prefix').strip()
      File "/private/var/folders/_q/bnvmgm191hz962m9y1gcstqw0000gq/T/pip-install-crivcl09/pygsl_aa60613eeea3405eb880491abe461bed/gsl_dist/gsl_Extension.py", line 114, in get_gsl_info
        raise DistutilsExecError("could not start %s"%self.gsl_config_tool)
    distutils.errors.DistutilsExecError: could not start gsl-config
    No array object was selected.
    No array object was selected.
    Looking for a suitable array moduleSELECTED a NEW array module ->numpy
    Please make sure that all modules are built with the same setting.
    e.g. remove the build directory and start the build process again!
    numpy
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/38/d9/ac760af4d74a99d757bf93c5d29dd7847ad40b761d090527b69484f4ac5b/pygsl-2.1.1.tar.gz#sha256=052ef186d499332a325edd0d46a0f9ae0726050da07f2328cfd659d620e2be33 (from https://pypi.org/simple/pygsl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
_ERROR: Could not find a version that satisfies the requirement pygsl (from versions: 2.1.1, 2.3.0.1, 2.3.2)
ERROR: No matching distribution found for pygsl_
**(base) Phy8s-Mac-Studio:~ adwaitkulkarni$**

**Comment by clinssen** [comment]
Note the line that says:

`` /bin/sh: gsl-config: command not found``

Do you have GSL installed? Please check your paths so the binary file can be located by the PyGSL installer script.
