### ISSUE TITLE
Can't install on Windows via pip

### ISSUE THREAD

**Issue by milen-prg** [pygsl/pygsl#27]
Windows 10 Pro 64bit, Python 3.11.4:

pip install -U pygsl

Collecting pygsl
  Downloading pygsl-2.3.3.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "C:\Users\mlap\AppData\Local\Temp\pip-install-43om8uhc\pygsl_79de1370e4ec4a408c9b2e164f15cda6\gsl_dist\gsl_Location.py", line 141, in __init__
          import gsl_site
      ModuleNotFoundError: No module named 'gsl_site'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mlap\AppData\Local\Temp\pip-build-env-4r14593i\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mlap\AppData\Local\Temp\pip-build-env-4r14593i\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\mlap\AppData\Local\Temp\pip-build-env-4r14593i\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 99, in <module>
        File "C:\Users\mlap\AppData\Local\Temp\pip-install-43om8uhc\pygsl_79de1370e4ec4a408c9b2e164f15cda6\gsl_dist\gsl_Extension.py", line 22, in <module>
          from gsl_Location import gsl_Location
        File "C:\Users\mlap\AppData\Local\Temp\pip-install-43om8uhc\pygsl_79de1370e4ec4a408c9b2e164f15cda6\gsl_dist\gsl_Location.py", line 160, in <module>
          gsl_Location = _gsl_Location_file()
                         ^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mlap\AppData\Local\Temp\pip-install-43om8uhc\pygsl_79de1370e4ec4a408c9b2e164f15cda6\gsl_dist\gsl_Location.py", line 148, in __init__
          raise DistutilsExecError(msg % des)
      distutils.errors.DistutilsExecError: I do not know how to run gsl-config
      on this system. Therefore you must provide me with the information
      where to find the GSL library. I could not import `gsl_site'.
      Reason: No module named 'gsl_site'. Copy gsl_site_example.py to gsl_site.py.
      Edit the variables in that file to reflect your installation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by CrazyCreepy** [comment]
Hi @milen-prg  I have the same issue when I try to switch to tyhe python 3.6 to 3.11.4 because Visual Code Studio can't use python 3.6.  I don't have the solution, but I have some clues about the issue. 

First, we try to use this package with python 3.11  when it's only be test with the version 3.8. So that normal that we have some issue there. 

Second, like you said is not the pip the issue, but is a missing file in the tempoary file that was download. 
To be precisly it's the gsl_site.py that not in the reposity. If you download the [new release](https://github.com/pygsl/pygsl/releases) an go to [extract file]\pygsl-2.3.3\gsl_dist the no gsl_site.py.
You need to create this file with this in it:
```
# Some systems do not provide gsl-config. So here the locations can be entered
 # by hand.
 import os

# The path to the directory where gsl is installed. Currently setup.py assumes
# that the include files are located in "prefix/include". 
prefix = os.path.join("C:\\", "OpenSource", "local")

cflags = "-g -I" + os.path.join(prefix, "include")

libs   = "-L" + os.path.join(prefix, "lib")+ " -lgsl -lgslcblas -lm"

# Enter the correct GSL versions by hand..
version = "2.7"

# swig_extension.py needs swig to generate the approbriate wrapper files. This
# variable only needs to be correct is you use USE_SWIG=1 in setup.py
swig = os.path.join("C:\\", "OpenSource", "swig", "swig-4.1.1", "swig")
#swig = os.path.join("C:\\", "Programs", "Swig", "SWIG-1.3.19", "swig")
```

Also, be sure to have the latest wheel package and swig pacakge. 
Afther that open a bash command and type  `python setup.py gsl_wrappers`

the result should be:
```
<swig_extension.SWIG_Extension('__callback') at 0x25b364dc350>
Building testing ufuncs!
#29 extension modules
running gsl_wrappers
Exporting parser tree using swig: ['C:\\OpenSource\\swig\\swig-4.1.1\\swig', '-I
C:\\OpenSource\\local\\include', '-xml', 'C:\\Users\\Alexandre\\Downloads\\pygsl
-2.3.3.tar\\pygsl-2.3.3\\pygsl-2.3.3\\testing\\src\\sf\\sf.i']
error: [WinError 2] The system cannot find the file specified
```
 Now that where I am I need to figure it out how to solve this swig error.

The other option like mention [here](https://github.com/pygsl/pygsl/issues/19#issuecomment-1294812067) is to install manually GSL Library and rebuild the Wrapper from scrath.

If you want all step I made with more detail. I have post [a question](https://stackoverflow.com/questions/76886874/error-installing-pygsl-with-pip-modulenotfounderror-no-module-named-gsl-site) on stack.
