### ISSUE TITLE
could not start gsl-config

### ISSUE THREAD

**Issue by adwaitk06** [pygsl/pygsl#34]
I was installing pygsl on my mac. Its updated mac with Mac Os Sonoma (Version 14.0 (23A344)). As  Written in documentation i Followed all instructions for installations. 
Here its terminal code:

Phy8s-Mac-Studio:~ adwaitkulkarni$ conda install wheel
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.10.0

Please update conda by running

     conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0

All requested packages already installed.

Phy8s-Mac-Studio:~ adwaitkulkarni$ cd Downloads/

Phy8s-Mac-Studio:Downloads adwaitkulkarni$ cd pygsl.2.3.3
-bash: cd: pygsl.2.3.3: No such file or directory

Phy8s-Mac-Studio:Downloads adwaitkulkarni$ cd pygsl-2.3.3

Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ python3 setup.py gsl_wrappers
Traceback (most recent call last):
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/setup.py", line 92, in <module>
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
ModuleNotFoundError: No module named 'wheel'

Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ conda activate

(base) Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ python3 setup.py gsl_wrappers
/bin/sh: gsl-config: command not found
Traceback (most recent call last):
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/setup.py", line 99, in <module>
    from gsl_Extension import gsl_Extension
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/gsl_Extension.py", line 22, in <module>
    from gsl_Location import gsl_Location
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/gsl_Location.py", line 158, in <module>
    gsl_Location = _gsl_Location_gsl_config()
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/gsl_Location.py", line 111, in __init__
    self.prefix         = self.get_gsl_info('--prefix').strip()
  File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/gsl_Location.py", line 133, in get_gsl_info
    raise DistutilsExecError("could not start %s"%self.gsl_config_tool)
distutils.errors.DistutilsExecError: could not start gsl-config

$(base) Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$

**Comment by PierreSchnizer** [comment]
Please could you type on your command line gsl-config?

My assumption would be that gsl is not installed on your mac.


Sincerely yours

   Pierre


    --------------------Ursprüngliche Nachricht--------------------
    Von: adwaitk06 ***@***.***>
    Gesendet: Dienstag 7. November 2023 12:19
    An: pygsl/pygsl ***@***.***>
    CC: Subscribed ***@***.***>
    Betreff: [pygsl/pygsl] could not start gsl-config (Issue #34)

   
    I was installing pygsl on my mac. Its updated mac with Mac Os Sonoma
    (Version 14.0 (23A344)). As Written in documentation i Followed all
    instructions for installations.
    Here its terminal code:

    Phy8s-Mac-Studio:~ adwaitkulkarni$ conda install wheel
    Collecting package metadata (current_repodata.json): done
    Solving environment: done

    ==> WARNING: A newer version of conda exists. <==
    current version: 23.3.1
    latest version: 23.10.0

    Please update conda by running

     conda update -n base -c defaults conda

    Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0

    All requested packages already installed.

    Phy8s-Mac-Studio:~ adwaitkulkarni$ cd Downloads/

    Phy8s-Mac-Studio:Downloads adwaitkulkarni$ cd pygsl.2.3.3
    -bash: cd: pygsl.2.3.3: No such file or directory

    Phy8s-Mac-Studio:Downloads adwaitkulkarni$ cd pygsl-2.3.3

    Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ python3 setup.py gsl_wrappers
    Traceback (most recent call last):
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/setup.py", line 92, in
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    ModuleNotFoundError: No module named 'wheel'

    Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ conda activate

    (base) Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$ python3 setup.py
    gsl_wrappers
    /bin/sh: gsl-config: command not found
    Traceback (most recent call last):
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/setup.py", line 99, in
    from gsl_Extension import gsl_Extension
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/
    gsl_Extension.py", line 22, in
    from gsl_Location import gsl_Location
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/
    gsl_Location.py", line 158, in
    gsl_Location = _gsl_Location_gsl_config()
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/
    gsl_Location.py", line 111, in init
    self.prefix = self.get_gsl_info('--prefix').strip()
    File "/Users/adwaitkulkarni/Downloads/pygsl-2.3.3/gsl_dist/
    gsl_Location.py", line 133, in get_gsl_info
    raise DistutilsExecError("could not start %s"%self.gsl_config_tool)
    distutils.errors.DistutilsExecError: could not start gsl-config

    $(base) Phy8s-Mac-Studio:pygsl-2.3.3 adwaitkulkarni$

    —
    Reply to this email directly, view it on GitHub, or unsubscribe.
    You are receiving this because you are subscribed to this thread.Message
    ID: ***@***.***>

**Comment by adwaitk06** [comment]
Yes it was not present before so I installed it on mac.
I have installed wheel.
python setup.py gsl_wrappers
python setup.py config
then 
sudo python setup.py install
But now it is showing this error: 

error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/adwaitkulkarni/Documents/apps/anaconda3/include -arch arm64 -I/Users/adwaitkulkarni/Documents/apps/anaconda3/include -fPIC -O2 -isystem /Users/adwaitkulkarni/Documents/apps/anaconda3/include -arch arm64 -DSWIG_COBJECT_TYPES=1 -DDEBUG=1 -DPyGSL_SET_GSL_ERROR_HANDLER=1 -DNUMERIC=0 -UNDEBUG -I/opt/homebrew/Cellar/gsl/2.7.1/include -IInclude -I. -I/Users/adwaitkulkarni/Documents/apps/anaconda3/lib/python3.9/site-packages/numpy/core/include -I/Users/adwaitkulkarni/Documents/apps/anaconda3/include/python3.9 -c swig_src/hankel_wrap.c -o build/temp.macosx-11.1-arm64-cpython-39/swig_src/hankel_wrap.o" failed with exit status 1

how to rectify it??

**Comment by PierreSchnizer** [comment]
Please could you make some more checks:

  • I guess not necessary, but could you please check that python is version 3.
  • Is there some more error output from the compiler ?
  • If not could you please check if
      □ swig_src/hankel_wrap.c exists
      □ if running python setup.py build produces more output ?

Thx

  Pierre



    --------------------Ursprüngliche Nachricht--------------------
    Von: adwaitk06 ***@***.***>
    Gesendet: Freitag 17. November 2023 9:52
    An: pygsl/pygsl ***@***.***>
    CC: Pierre Schnizer ***@***.***>; Comment
    ***@***.***>
    Betreff: Re: [pygsl/pygsl] could not start gsl-config (Issue #34)

   
    Yes it was not present before so I installed it on mac.
    I have installed wheel.
    python setup.py gsl_wrappers
    python setup.py config
    then
    sudo python setup.py install
    But now it is showing this error:

    error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code
    -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/adwaitkulkarni/
    Documents/apps/anaconda3/include -arch arm64 -I/Users/adwaitkulkarni/
    Documents/apps/anaconda3/include -fPIC -O2 -isystem /Users/adwaitkulkarni/
    Documents/apps/anaconda3/include -arch arm64 -DSWIG_COBJECT_TYPES=1 -DDEBUG
    =1 -DPyGSL_SET_GSL_ERROR_HANDLER=1 -DNUMERIC=0 -UNDEBUG -I/opt/homebrew/
    Cellar/gsl/2.7.1/include -IInclude -I. -I/Users/adwaitkulkarni/Documents/
    apps/anaconda3/lib/python3.9/site-packages/numpy/core/include -I/Users/
    adwaitkulkarni/Documents/apps/anaconda3/include/python3.9 -c swig_src/
    hankel_wrap.c -o build/temp.macosx-11.1-arm64-cpython-39/swig_src/
    hankel_wrap.o" failed with exit status 1

    how to rectify it??

    —
    Reply to this email directly, view it on GitHub, or unsubscribe.
    You are receiving this because you commented.Message ID: <pygsl/pygsl/
    ***@***.***>
