### ISSUE TITLE
[BUG] Install Error

### ISSUE THREAD

**Issue by milen-prg** [pygsl/pygsl#59]
Windows 11 Pro 64bit,

❯ py -3.13 -m pip install -U pygsl
Collecting pygsl
  Using cached pygsl-2.3.3.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-fs5z1uf_\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-fs5z1uf_\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-fs5z1uf_\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 99, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-0y_an_eh\pygsl_4fc9906108104c4eb207731a0c77eef2\gsl_dist\gsl_Extension.py", line 19, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

=============================

P. S.
up to python 3.11 => imp python 3.12+ ==> importlib

P. P. S. Please, make possible to use GSL in newest Python in Windows 11!!!

**Comment by PierreSchnizer** [comment]
The main show stopper for pygsl on windows is having gsl compiled and linked. 

The last time I compiled gsl on windows is now more than 5 years ago.
Furthermore I have no access to a windows box.

If you have gsl as binary on your windows machine it could be possible. Please try to download the latest release from this side and to build it

**Comment by PierreSchnizer** [comment]
e.g. python3 -m pip install -v  https://github.com/pygsl/pygsl/archive/refs/tags/v2.4.1.tar.gz
